### ISSUE TITLE
Build Agent: Request "zip on linux"

### ISSUE THREAD

**Issue by ndeeH** [whiteducksoftware/azure-devops-build-agents-community#4]
Hello,  
none of the standard azure dev ops deploy jobs work because your agents don't have the zip utility on them. How do I get this on and why do they not include it? 
It would seem pretty standard but now I have to spend a long time figuring out how to best do this.

**Comment by mjisaak** [comment]
adding @StiviiK / @dariobro

**Comment by ndeeH** [comment]
I think this issue is related to our **Single Windows VM plan**.
We do not install initially an archiver in our Hosted Build Agent yet.

As far as I can see the most tasks use 7Zip directly or as fallback.
We will add **7Zip** via Chocolaty in the initial configuration of the VM in our next update.
You may connect to the vm image and install 7Zip via: 
`choco install 7zip`

**Comment by nmeisenzahl** [comment]
@ndeeH We should verify that we do not get any licensing issues here. Are we allowed to distribute 7zip in our offering?

**Comment by ndeeH** [comment]
Zip/Unzip support added to both plans - see [Release Notes](https://github.com/whiteducksoftware/azure-devops-build-agents-community/discussions/5)
Additional packages should be added in scale set docker images.
